apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo-app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: rimap2610/python-app-image:v1.0-436-20240915-161016
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          resources:
            requests:
               memory: "236Mi"
               cpu: "100m"
            limits:
               memory: "512Mi"
               cpu: "200"
